import { createClient } from '@supabase/supabase-js'
import { fetchFeed } from '@/lib/news/ingest'
import type { FeedSource, SourceType } from '@/lib/news/types'

export const runtime='nodejs'
export const dynamic='force-dynamic'

function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase server credentials are not configured');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})}
function titleTokens(title:string){return new Set(title.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').split(/\s+/).filter(w=>w.length>2&&!['the','and','for','with','from','that','this','are','was','has','have'].includes(w)))}
function similarity(a:string,b:string){const x=titleTokens(a),y=titleTokens(b);if(!x.size||!y.size)return 0;let shared=0;for(const token of x)if(y.has(token))shared++;return shared/Math.max(1,Math.min(x.size,y.size))}

export async function GET(request:Request){const expected=process.env.CRON_SECRET??process.env.AUTOMATION_CRON_SECRET;if(!expected||request.headers.get('authorization')!==`Bearer ${expected}`)return Response.json({error:'Unauthorized'},{status:401});const supabase=db();const{data:run,error:runError}=await supabase.from('automation_runs').insert({job_type:'feed_ingestion',status:'running'}).select('id').single();if(runError)return Response.json({error:runError.message},{status:500});const{data:sources,error:sourceError}=await supabase.from('sources').select('id,name,feed_url,homepage_url,source_type,category,country,enabled').eq('enabled',true);if(sourceError){await supabase.from('automation_runs').update({status:'failed',finished_at:new Date().toISOString(),error_message:sourceError.message}).eq('id',run.id);return Response.json({error:'Could not load sources'},{status:500})}
 let storiesDiscovered=0,storiesProcessed=0,errors=0;const results=[]
 for(const source of sources??[]){const feedSource:FeedSource={id:source.id,name:source.name,feedUrl:source.feed_url,homepageUrl:source.homepage_url,sourceType:source.source_type as SourceType,category:source.category,country:source.country,enabled:source.enabled};try{const stories=await fetchFeed(feedSource);storiesDiscovered+=stories.length;let processed=0;for(const story of stories){const{data:saved,error}=await supabase.from('stories').upsert({source_id:story.sourceId,external_id:story.externalId,canonical_url:story.canonicalUrl,title:story.title,description:story.description,author:story.author,published_at:story.publishedAt,content_hash:story.contentHash,language:story.language,category:story.category,country:story.country,image_url:story.imageUrl,metadata:story.metadata},{onConflict:'source_id,canonical_url'}).select('id,title,category,country').single();if(error)throw error;processed++;if(saved){const{data:recent}=await supabase.from('stories').select('id,title,category,country').neq('id',saved.id).order('created_at',{ascending:false}).limit(100);const match=recent?.find(r=>(r.category||null)===(saved.category||null)&&(r.country||null)===(saved.country||null)&&similarity(r.title,saved.title)>=0.65);if(match){let{data:cluster}=await supabase.from('story_cluster_members').select('cluster_id').eq('story_id',match.id).maybeSingle();if(!cluster){const{data:newCluster}=await supabase.from('story_clusters').insert({title:match.title,category:match.category,country:match.country}).select('id').single();if(newCluster){cluster={cluster_id:newCluster.id};await supabase.from('story_cluster_members').insert({cluster_id:newCluster.id,story_id:match.id})}}if(cluster)await supabase.from('story_cluster_members').upsert({cluster_id:cluster.cluster_id,story_id:saved.id},{onConflict:'cluster_id,story_id'})}}}storiesProcessed+=processed;const now=new Date().toISOString();await supabase.from('sources').update({last_checked_at:now,last_success_at:now,last_error:null}).eq('id',source.id);results.push({source:source.name,fetched:stories.length,processed})}catch(error){errors++;const message=error instanceof Error?error.message:'Unknown feed error';await supabase.from('sources').update({last_checked_at:new Date().toISOString(),last_error:message}).eq('id',source.id);results.push({source:source.name,error:message})}}
 await supabase.from('automation_runs').update({status:errors&&!storiesProcessed?'failed':'completed',finished_at:new Date().toISOString(),sources_checked:sources?.length??0,stories_discovered:storiesDiscovered,stories_processed:storiesProcessed,metadata:{results}}).eq('id',run.id);return Response.json({ok:true,sourcesChecked:sources?.length??0,storiesDiscovered,storiesProcessed,errors,results})}
