'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Story = { id:string; title:string; description:string|null; author:string|null; canonical_url:string; category:string|null; country:string|null; language:string|null; status:string; published_at:string|null; created_at:string; source_id:string; image_url:string|null }

export default function StoryReviewPage(){
 const{id}=useParams<{id:string}>();const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[story,setStory]=useState<Story|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[creating,setCreating]=useState(false)
 useEffect(()=>{let active=true;(async()=>{const{data,error}=await supabase.from('stories').select('*').eq('id',id).single();if(!active)return;if(error)setError(error.message);else setStory(data as Story)})();return()=>{active=false}},[id,supabase])
 async function setStatus(status:'approved'|'rejected'|'review'){if(!story)return;setBusy(true);setError('');const{data,error}=await supabase.from('stories').update({status}).eq('id',story.id).select('*').single();if(error)setError(error.message);else setStory(data as Story);setBusy(false)}
 async function approveAndCreate(){if(!story)return;setCreating(true);setError('');const{data:approved,error:approvalError}=await supabase.from('stories').update({status:'approved'}).eq('id',story.id).select('*').single();if(approvalError){setError(approvalError.message);setCreating(false);return}setStory(approved as Story);const r=await fetch('/api/admin/briefs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storyId:story.id})});const data=await r.json();if(!r.ok){setError(data.error||'Approved, but could not create the draft briefing.');setCreating(false);return}router.push(`/admin/briefs/${data.id}`)}
 if(error&&!story)return <main className="site"><div className="content admin-content"><Link href="/admin/inbox">← Story Inbox</Link><section className="empty-state"><h3>Could not load story</h3><p>{error}</p></section></div></main>
 if(!story)return <main className="site"><div className="content admin-content"><p className="muted">Loading story…</p></div></main>
 return <main className="site"><header className="header"><div className="header-inner"><Link className="brand" href="/admin">READ-A-BRIEF <span>/ REVIEW</span></Link><nav className="nav"><Link href="/admin/inbox">Story Inbox</Link><Link href="/admin/sources">Sources</Link><Link href="/">Public site</Link></nav></div></header><div className="content admin-content"><Link className="muted" href="/admin/inbox">← Back to Story Inbox</Link><article className="card" style={{marginTop:20}}>{story.image_url?<div className="image-frame" style={{aspectRatio:'16/7',margin:'-22px -22px 24px',width:'calc(100% + 44px)'}}><img src={story.image_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>:<div className="image-placeholder" style={{margin:'-22px -22px 24px',width:'calc(100% + 44px)',minHeight:180}}><span>{story.category||'NEWS'}</span></div>}<div className="tag">{story.status.toUpperCase()} · {story.category||'UNCATEGORIZED'}</div><h1>{story.title}</h1><p className="muted">{story.country||'Global'}{story.author?` · ${story.author}`:''} · {new Date(story.created_at).toLocaleString()}</p>{story.description&&<p style={{fontSize:18,lineHeight:1.7}}>{story.description}</p>}<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}><button disabled={busy||creating} onClick={approveAndCreate}>{creating?'Approving & creating…':'✓ Approve & create brief'}</button><button disabled={busy||creating} onClick={()=>setStatus('review')}>Keep in review</button><button disabled={busy||creating} onClick={()=>setStatus('rejected')}>Reject</button><a className="button-link" href={story.canonical_url} target="_blank" rel="noreferrer">Open original ↗</a></div>{story.status==='approved'&&<p className="muted" style={{marginTop:12}}>Approved. You can create the draft briefing above.</p>}{error&&<p className="auth-error" style={{marginTop:14}}>{error}</p>}</article></div></main>
}
