import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export const dynamic='force-dynamic'
type Brief={id:string;headline:string;dek:string|null;summary:string|null;body:string|null;why_it_matters:string|null;what_happens_next:string|null;category:string|null;country:string|null;language:string|null;image_url:string|null;published_at:string|null;created_at:string}
type BriefSource={source_name:string;source_url:string;attribution:string|null}

export default async function BriefPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createClient();const[{data:brief},{data:sources}]=await Promise.all([
  supabase.from('briefs').select('id,headline,dek,summary,body,why_it_matters,what_happens_next,category,country,language,image_url,published_at,created_at').eq('id',id).eq('status','published').maybeSingle<Brief>(),
  supabase.from('brief_sources').select('source_name,source_url,attribution').eq('brief_id',id)
 ]); if(!brief)notFound()
 return <main className="site"><header className="header"><div className="header-inner"><Link className="brand" href="/">READ-A-BRIEF <span>/ BRIEFING</span></Link><nav className="nav"><Link href="/">← All briefings</Link><Link href="/auth/login">Sign in</Link></nav></div></header><article className="article-shell">{brief.image_url?<div className="article-hero-image"><img src={brief.image_url} alt=""/></div>:<div className="article-hero-placeholder"><span>{brief.category||'NEWS'}</span></div>}<div className="article-meta"><span className="tag">{brief.category||brief.country||'News'}</span><span>{brief.published_at?new Date(brief.published_at).toLocaleDateString():'Published'}</span></div><h1>{brief.headline}</h1>{brief.dek&&<p className="article-dek">{brief.dek}</p>}{brief.summary&&<section className="article-lead"><strong>THE BRIEF</strong><p>{brief.summary}</p></section>}{brief.body&&<div className="article-body">{brief.body.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div>}{(brief.why_it_matters||brief.what_happens_next)&&<div className="article-grid">{brief.why_it_matters&&<section className="article-note"><span>WHY IT MATTERS</span><p>{brief.why_it_matters}</p></section>}{brief.what_happens_next&&<section className="article-note"><span>WHAT HAPPENS NEXT</span><p>{brief.what_happens_next}</p></section>}</div>}<section className="card" style={{marginTop:28}}><div className="tag">SOURCES</div><h3>Reporting & attribution</h3><p className="muted">Read-a-Brief produces original summaries and does not republish source articles.</p>{sources&&sources.length>0?<div style={{display:'grid',gap:10,marginTop:12}}>{(sources as BriefSource[]).map((s,i)=><div key={`${s.source_url}-${i}`}><a href={s.source_url} target="_blank" rel="noreferrer"><strong>{s.source_name}</strong> ↗</a>{s.attribution&&<p className="muted">{s.attribution}</p>}</div>)}</div>:<p className="muted">Source information unavailable.</p>}</section><footer className="article-footer"><span>{brief.country||'Global'} · {brief.language||'English'}</span><Link href="/">More briefings →</Link></footer></article></main>
}
