'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Brief = { id:string; headline:string; dek:string|null; summary:string|null; why_it_matters:string|null; what_happens_next:string|null; body:string|null; category:string|null; country:string|null; language:string|null; confidence:number|null; status:string; published_at:string|null }

export default function BriefEditor(){
  const {id}=useParams<{id:string}>(); const router=useRouter(); const supabase=useMemo(()=>createClient(),[])
  const [brief,setBrief]=useState<Brief|null>(null); const [error,setError]=useState(''); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;(async()=>{const{data,error}=await supabase.from('briefs').select('*').eq('id',id).single();if(!active)return;if(error)setError(error.message);else setBrief(data as Brief)})();return()=>{active=false}},[id,supabase])
  function setField<K extends keyof Brief>(key:K,value:Brief[K]){setBrief(b=>b?{...b,[key]:value}:b)}
  async function save(publish=false){if(!brief)return;setBusy(true);setError('');setStatus('Saving…');if(!brief.headline.trim()||!brief.summary?.trim()){setError('Headline and summary are required.');setBusy(false);return}if(publish&&!brief.body?.trim()){setError('Add the briefing body before publishing.');setBusy(false);return}
    const payload={headline:brief.headline.trim(),dek:brief.dek||null,summary:brief.summary.trim(),why_it_matters:brief.why_it_matters||null,what_happens_next:brief.what_happens_next||null,body:brief.body||null,category:brief.category||null,country:brief.country||null,language:brief.language||'English',confidence:brief.confidence, status:publish?'published':brief.status==='published'?'approved':'review', published_at:publish?new Date().toISOString():null, reviewed_at:publish?new Date().toISOString():null}
    const{data,error}=await supabase.from('briefs').update(payload).eq('id',brief.id).select('*').single();if(error)setError(error.message);else{setBrief(data as Brief);setStatus(publish?'Published successfully.':'Saved.');if(publish)router.refresh()}setBusy(false)}
  if(error&&!brief)return <main className="site"><div className="content admin-content"><Link href="/admin">← Operations</Link><section className="empty-state"><h3>Could not load brief</h3><p>{error}</p></section></div></main>
  if(!brief)return <main className="site"><div className="content admin-content"><p className="muted">Loading brief…</p></div></main>
  const input=(key:keyof Brief,label:string,placeholder:string,multiline=false)=><label style={{display:'grid',gap:7}}><span className="tag">{label}</span>{multiline?<textarea rows={key==='body'?10:5} value={String(brief[key]??'')} placeholder={placeholder} onChange={e=>setField(key,e.target.value as never)}/>:<input value={String(brief[key]??'')} placeholder={placeholder} onChange={e=>setField(key,e.target.value as never)}/>}</label>
  return <main className="site"><header className="header"><div className="header-inner"><Link className="brand" href="/admin">READ-A-BRIEF <span>/ EDITOR</span></Link><nav className="nav"><Link href="/admin/inbox">Inbox</Link><Link href="/admin">Dashboard</Link><Link href="/">Public site</Link></nav></div></header><div className="content admin-content"><Link className="muted" href="/admin/inbox">← Story Inbox</Link><div className="section-head" style={{marginTop:18}}><div><div className="eyebrow">Editorial briefing</div><h2>Edit & publish</h2></div><span className={`status status-${brief.status}`}>{brief.status}</span></div><section className="card" style={{display:'grid',gap:16}}>{input('headline','HEADLINE','What happened?')}{input('dek','DEK','One-sentence context')}{input('summary','THE BRIEF','Concise summary',true)}{input('why_it_matters','WHY IT MATTERS','Why should readers care?',true)}{input('what_happens_next','WHAT HAPPENS NEXT','What to watch next',true)}{input('body','BODY','Full original briefing',true)}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12}}>{input('category','CATEGORY','World')}{input('country','COUNTRY','Uganda')}{input('language','LANGUAGE','English')}</div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button disabled={busy} onClick={()=>save(false)}>Save draft</button><button disabled={busy} onClick={()=>save(true)}>Approve & publish</button>{brief.status==='published'&&<Link className="button-link" href={`/brief/${brief.id}`}>View public brief ↗</Link>}</div>{status&&<p className="muted">{status}</p>}{error&&<p className="auth-error">{error}</p>}</section></div></main>
}
